#------------------------------------------------------------------------------
# DRAT Prototype Tool Source Code
# 
# Copyright 2019 Carnegie Mellon University. All Rights Reserved.
# 
# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING 
# INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
# UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS
# TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE
# OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE
# MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND
# WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
# 
# Released under a MIT (SEI)-style license, please see license.txt or contact
# permission@sei.cmu.edu for full terms.
# 
# [DISTRIBUTION STATEMENT A] This material has been approved for public
# release and unlimited distribution.  Please see Copyright notice for non-US
# Government use and distribution.
# 
# This Software includes and/or makes use of the following Third-Party
# Software subject to its own license:
# 
# 1. Python 3.7 (https://docs.python.org/3/license.html)
# Copyright 2001-2019 Python Software Foundation.
# 
# 2. SQL Alchemy (https://github.com/sqlalchemy/sqlalchemy/blob/master/LICENSE)
# Copyright 2005-2019 SQLAlchemy authors and contributor.
# 
# DM19-0055
#------------------------------------------------------------------------------

"""Add hostname and port to System dao

Revision ID: c211a0faa8d5
Revises: 0d8ea58e5a0c
Create Date: 2018-08-16 10:26:01.081634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'c211a0faa8d5'
down_revision = '0d8ea58e5a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systems', sa.Column('hostname', sa.String(length=253), nullable=True))
    op.add_column('systems', sa.Column('port', sa.Integer(), nullable=True))

    conn = op.get_bind()

    conn.execute(
        text(
            """
UPDATE systems
SET name = remote_name
   ,hostname = COALESCE ( NULLIF (name, ''), remote_name)
   ,port = 22
            """
        )
    )

    op.alter_column('systems', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('systems', 'hostname',
               existing_type=sa.VARCHAR(length=253),
               nullable=False)
    op.alter_column('systems', 'port',
               existing_type=sa.INTEGER,
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('systems', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('systems', 'port')
    op.drop_column('systems', 'hostname')
    # ### end Alembic commands ###
