#------------------------------------------------------------------------------
# DRAT Prototype Tool Source Code
# 
# Copyright 2019 Carnegie Mellon University. All Rights Reserved.
# 
# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING 
# INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
# UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS
# TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE
# OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE
# MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND
# WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
# 
# Released under a MIT (SEI)-style license, please see license.txt or contact
# permission@sei.cmu.edu for full terms.
# 
# [DISTRIBUTION STATEMENT A] This material has been approved for public
# release and unlimited distribution.  Please see Copyright notice for non-US
# Government use and distribution.
# 
# This Software includes and/or makes use of the following Third-Party
# Software subject to its own license:
# 
# 1. Python 3.7 (https://docs.python.org/3/license.html)
# Copyright 2001-2019 Python Software Foundation.
# 
# 2. SQL Alchemy (https://github.com/sqlalchemy/sqlalchemy/blob/master/LICENSE)
# Copyright 2005-2019 SQLAlchemy authors and contributor.
# 
# DM19-0055
#------------------------------------------------------------------------------

"""Add cascading deletes for file_storage table

Revision ID: c71b22569370
Revises: a33a033940b0
Create Date: 2018-09-14 12:44:36.636086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71b22569370'
down_revision = 'a33a033940b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('file_detail_storage_link_file_storage_id_fkey', 'file_detail_storage_link', type_='foreignkey')
    op.create_foreign_key(None, 'file_detail_storage_link', 'file_storage', ['file_storage_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('rpm_detail_patch_storage_link_file_storage_id_fkey', 'rpm_detail_patch_storage_link', type_='foreignkey')
    op.create_foreign_key(None, 'rpm_detail_patch_storage_link', 'file_storage', ['file_storage_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rpm_detail_patch_storage_link', type_='foreignkey')
    op.create_foreign_key('rpm_detail_patch_storage_link_file_storage_id_fkey', 'rpm_detail_patch_storage_link', 'file_storage', ['file_storage_id'], ['id'])
    op.drop_constraint(None, 'file_detail_storage_link', type_='foreignkey')
    op.create_foreign_key('file_detail_storage_link_file_storage_id_fkey', 'file_detail_storage_link', 'file_storage', ['file_storage_id'], ['id'])
    # ### end Alembic commands ###
